[package]
name = "dbt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
regex = "1"
structopt = "0.3"
env_logger = "0.9"
log = "0.4"
memchr = "2.4.1"
