[workspace]
# FIXME: For some reason Cargo does not support `members = ["*"]` on Windows
members = ["basics", "ignored_test", "crashdump", "crashdump_import_export", "async_stack_traces"]
exclude = ["target"]

[profile.dev]
codegen-units = 1

[profile.release]
debug = 2
codegen-units = 1
